// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<string>;

export function GetFiles(arg1:number,arg2:number):Promise<Array<Record<string, any>>>;

export function GetIndexingStatus():Promise<main.IndexingStatus>;

export function GetSystemStatus():Promise<main.SystemStatus>;

export function PauseIndexing():Promise<void>;

export function ResetDatabase():Promise<void>;

export function ResumeIndexing():Promise<void>;

export function Search(arg1:main.SearchRequest):Promise<Array<main.SearchResult>>;

export function StartIndexing(arg1:string):Promise<void>;

export function StopIndexing():Promise<void>;

export function UpdateConfig(arg1:string):Promise<void>;
