// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallAPI(arg1, arg2, arg3) {
  return window['go']['main']['App']['CallAPI'](arg1, arg2, arg3);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFiles(arg1, arg2) {
  return window['go']['main']['App']['GetFiles'](arg1, arg2);
}

export function GetIndexingStatus() {
  return window['go']['main']['App']['GetIndexingStatus']();
}

export function GetSystemStatus() {
  return window['go']['main']['App']['GetSystemStatus']();
}

export function IsLLMQuery(arg1) {
  return window['go']['main']['App']['IsLLMQuery'](arg1);
}

export function PauseIndexing() {
  return window['go']['main']['App']['PauseIndexing']();
}

export function ResetDatabase() {
  return window['go']['main']['App']['ResetDatabase']();
}

export function ResumeIndexing() {
  return window['go']['main']['App']['ResumeIndexing']();
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SearchWithDetails(arg1) {
  return window['go']['main']['App']['SearchWithDetails'](arg1);
}

export function StartIndexing(arg1) {
  return window['go']['main']['App']['StartIndexing'](arg1);
}

export function StopIndexing() {
  return window['go']['main']['App']['StopIndexing']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
